#!/usr/bin/expect

set password lxdiyun112045

spawn ssh -p 2232 admin@192.168.1.1

expect {
   -ex yes/no { 
      send "yes\r"; 

      expect "assword:" {
         send "$password\r";
      }
   }
   "assword:" { send "$password\r"; }
}

interact;

